### ISSUE TITLE
When do you think the code might be available? Thank you

### ISSUE THREAD

**Issue by b-delfino** [lzqsd/TransparentShapeReconstruction#2]

**Comment by lzqsd** [comment]
Sorry for our delay! I hope we can get it ready by the end of this week. Please check our project page for more updates. 
http://cseweb.ucsd.edu/~viscomp/projects/CVPR20Transparent/

**Comment by lzqsd** [comment]
Sorry we did not get it ready yet. Hope that it will be done this week :-).
